# fly.toml app configuration file generated for traffic-watch-little-forest-9366 on 2024-09-02T14:06:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'traffic-watch-little-forest-9366'
primary_region = 'iad'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'traffic-watch-little-forest-9366.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
